# Generated by Django 2.0.6 on 2018-07-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attending',
            name='attending',
            field=models.NullBooleanField(),
        ),
    ]
