# Generated by Django 2.0.6 on 2018-08-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180731_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='attending',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='api.Game'),
        ),
        migrations.AlterField(
            model_name='attending',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.IntegerField(choices=[(0, 'FEMALE'), (1, 'Male'), (2, 'UNKNOWN')], default=2),
        ),
    ]
